from __future__ import annotations

import json
from pathlib import Path


def _write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def build_run_meta(state: dict, generated_at: str) -> dict:
    return {
        "schema_version": "run_meta.v0",
        "case_id": state["meta"]["case_id"],
        "session_id": state["meta"]["session_id"],
        "timestamp": generated_at,
        "session_type": "benchmark_runtime_scaffold",
        "policy_profile": state["meta"]["policy_profile"],
        "runtime": {
            "environment": "local_scaffold",
            "code_version": "runtime-scaffold-v0",
            "git_commit_hash": None,
        },
        "model_config": {
            "provider": "deterministic_authored_scaffold",
            "model_name": "d_b04_baseline_reference",
            "temperature": 0,
            "other_decoding_settings": {},
        },
        "prompting": {
            "prompt_version": "baseline_scaffold_v0",
            "prompt_ids": [
                "solomon_core_baseline_v0",
                "divorce_plugin_baseline_v0",
                "d_b04_case_baseline_v0",
            ],
        },
        "randomization": {
            "seed": 404,
            "determinism_note": "This run is generated by the deterministic scaffold to validate contracts and architecture boundaries.",
        },
        "case_context": {
            "plugin_type": state["meta"]["plugin_type"],
            "source": state["meta"].get("source", "reference"),
            "process_variant": state["meta"].get("process_variant"),
            "participant_context": state["participants"],
        },
    }


def build_interaction_trace(state: dict, generated_at: str) -> dict:
    return {
        "schema_version": "interaction_trace.v0",
        "case_id": state["meta"]["case_id"],
        "session_id": state["meta"]["session_id"],
        "policy_profile": state["meta"]["policy_profile"],
        "trace_created_at": generated_at,
        "turns": state["trace_buffer"],
    }


def _position_note(state: dict) -> str:
    proposal_count = sum(len(participant["proposals"]) for participant in state["positions"].values())
    if proposal_count:
        return "The session ended with distinct starting positions preserved and only conditional openness to phased option work."
    return "The session ended with distinct starting positions preserved and no supported option movement yet."


def build_positions(state: dict) -> dict:
    return {
        "schema_version": "positions.v0",
        "case_id": state["meta"]["case_id"],
        "session_id": state["meta"]["session_id"],
        "participants": list(state["positions"].values()),
        "position_notes": _position_note(state),
    }


def _facts_note(state: dict) -> str:
    uncertain_count = sum(1 for fact in state["facts"] if fact["status"] == "uncertain")
    disputed_count = sum(1 for fact in state["facts"] if fact["status"] == "disputed")
    if uncertain_count and disputed_count:
        return "Uncertain feasibility items and disputed constraints remain visible rather than being promoted to settled conclusions."
    if uncertain_count:
        return "Uncertain feasibility items remain explicit rather than being promoted to settled conclusions."
    return "Facts remain separated from unresolved feasibility questions."


def build_facts_snapshot(state: dict) -> dict:
    return {
        "schema_version": "facts_snapshot.v0",
        "case_id": state["meta"]["case_id"],
        "session_id": state["meta"]["session_id"],
        "facts": state["facts"],
        "facts_notes": _facts_note(state),
    }


def _flag_notes(state: dict) -> str:
    active_types = {flag["flag_type"] for flag in state["flags"]}
    if "plugin_low_confidence" in active_types and "insufficient_information" in active_types:
        return "The session remained workable, but plugin confidence and unresolved information jointly narrowed the run into a caution posture."
    if "insufficient_information" in active_types:
        return "The session remained workable, but unresolved information narrowed the run into a caution posture."
    return "No caution-relevant flags remained active at close."


def build_flags(state: dict) -> dict:
    return {
        "schema_version": "flags.v0",
        "case_id": state["meta"]["case_id"],
        "session_id": state["meta"]["session_id"],
        "active_flags": state["flags"],
        "cleared_flags": [],
        "historical_flags": [],
        "flag_notes": _flag_notes(state),
    }


def _missing_info_note(state: dict) -> str:
    open_count = len([item for item in state["missing_info"] if item["status"] == "open"])
    if open_count >= 2:
        return "The unresolved items are explicit enough to justify M1 caution and block stronger schedule recommendation."
    if open_count == 1:
        return "A remaining unresolved item still limits stronger schedule recommendation."
    return "No unresolved missing-information items remained at close."


def build_missing_info(state: dict) -> dict:
    return {
        "schema_version": "missing_info.v0",
        "case_id": state["meta"]["case_id"],
        "session_id": state["meta"]["session_id"],
        "missing_items": state["missing_info"],
        "missing_info_notes": _missing_info_note(state),
    }


def _summary_positions(state: dict) -> list[str]:
    lines: list[str] = []
    for participant_id, participant in sorted(state["positions"].items()):
        label = "Parent A" if participant_id == "spouse_A" else "Parent B"
        if participant["current_positions"]:
            lines.append(f"- {label}: {participant['current_positions'][0]['statement']}")
    if any(participant["proposals"] for participant in state["positions"].values()):
        lines.append("- Both parents showed at least conditional openness to phased option work.")
    return lines


def _summary_facts(state: dict) -> list[str]:
    lines: list[str] = []
    accepted = [fact for fact in state["facts"] if fact["status"] == "accepted"]
    uncertain = [fact for fact in state["facts"] if fact["status"] == "uncertain"]
    disputed = [fact for fact in state["facts"] if fact["status"] == "disputed"]
    if accepted:
        lines.append(f"- Accepted: {accepted[0]['statement']}")
    if len(accepted) > 1:
        lines.append(f"- Accepted: {accepted[1]['statement']}")
    if uncertain:
        lines.append(f"- Unresolved: {uncertain[0]['statement']}")
    if disputed:
        lines.append(f"- Disputed: {disputed[0]['statement']}")
    return lines


def _summary_flags(state: dict) -> list[str]:
    lines = []
    for flag in state["flags"]:
        lines.append(f"- {flag['title']}.")
    return lines


def _summary_missing_items(state: dict) -> list[str]:
    return [f"- {item['question']}" for item in state["missing_info"] if item["status"] == "open"]


def _summary_intro(state: dict) -> str:
    issue_bits = [issue.lower() for issue in state["summary_state"]["issues"][:2]]
    issue_phrase = " and ".join(issue_bits) if issue_bits else "the key dispute"
    return (
        "Solomon framed the matter as a dispute involving "
        f"{issue_phrase}. It kept the process bounded, preserved uncertainty explicitly, "
        "and avoided presenting a fixed recommendation."
    )


def _escalation_lines(state: dict) -> list[str]:
    plugin_assessment = state.get("plugin_assessment", {})
    lines = [f"- `{state['escalation']['mode']}` with category `{state['escalation']['category'] or 'none'}`."]
    lines.append(f"- {state['escalation']['rationale']}")
    if plugin_assessment.get("warnings"):
        lines.append(f"- {plugin_assessment['warnings'][0]}")
    return lines


def build_summary(state: dict) -> str:
    issues = "\n".join(f"- {issue}" for issue in state["summary_state"]["issues"])
    source = state["meta"].get("source", "reference")
    process_variant = state["meta"].get("process_variant")
    process_line = f"Process Variant: {process_variant}\n" if process_variant else ""
    participant_lines = "\n".join(_summary_positions(state))
    fact_lines = "\n".join(_summary_facts(state))
    flag_lines = "\n".join(_summary_flags(state))
    missing_lines = "\n".join(_summary_missing_items(state))
    escalation_lines = "\n".join(_escalation_lines(state))
    return (
        "Session Summary\n"
        f"Run Source: {source}\n"
        f"{process_line}"
        f"{_summary_intro(state)}\n\n"
        "Issues Identified\n"
        f"{issues}\n\n"
        "Participant Positions\n"
        f"{participant_lines}\n\n"
        "Facts and Uncertainties\n"
        f"{fact_lines}\n\n"
        "Active Flags / Concerns\n"
        f"{flag_lines}\n\n"
        "Missing Information\n"
        f"{missing_lines}\n\n"
        "Current Escalation Posture\n"
        f"{escalation_lines}\n\n"
        "Recommended Next Step\n"
        f"{state['summary_state']['next_step']}\n"
    )


def write_artifacts(output_dir: Path, state: dict, generated_at: str) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    _write_json(output_dir / "run_meta.json", build_run_meta(state, generated_at))
    _write_json(output_dir / "interaction_trace.json", build_interaction_trace(state, generated_at))
    _write_json(output_dir / "positions.json", build_positions(state))
    _write_json(output_dir / "facts_snapshot.json", build_facts_snapshot(state))
    _write_json(output_dir / "flags.json", build_flags(state))
    _write_json(output_dir / "missing_info.json", build_missing_info(state))
    (output_dir / "summary.txt").write_text(build_summary(state), encoding="utf-8")
